In [1]:
10+3

13

In [2]:
2*3

6

In [3]:
2**3

8

In [5]:
x = 12
x

12

In [6]:
y = 15

In [7]:
x+y

27

In [8]:
'Hola mundo'

'Hola mundo'

In [11]:
x = 'Hola'
y = 'Mundo'
x + y

'HolaMundo'

In [12]:
x + ' ' + y

'Hola Mundo'

In [13]:
[1,2,3,5,6]

[1, 2, 3, 5, 6]

In [14]:
[1,2,3,5,6] + [2,3,5]

[1, 2, 3, 5, 6, 2, 3, 5]

In [15]:
lista = [1,2,3,4,5]

In [18]:
print(lista[0],lista[2])

1 3


In [21]:
[1,2,3,5,6] + [10]

[1, 2, 3, 5, 6, 10]

In [22]:
import numpy as np

In [24]:
np.array([1,2,3,4,5])+10

array([11, 12, 13, 14, 15])

In [25]:
np.array([1,2,3,4,5]).shape

(5,)

In [28]:
np.array([[1,2,3,4],[6,7,8,9]])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [29]:
np.array([[1,2,3,4],[6,7,8,9]]).shape

(2, 4)

In [30]:
np.array([[1,2,3,4],[6,7,8,9]])[0]

array([1, 2, 3, 4])

In [31]:
np.array([[1,2,3,4],[6,7,8,9]])[0][2]

3

In [32]:
import pandas as pd

In [33]:
pd.Series([10,9,8,7,6])

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [34]:
sr = pd.Series([10,9,8,7,6])

In [35]:
sr.index

RangeIndex(start=0, stop=5, step=1)

In [36]:
sr.shape

(5,)

In [37]:
sr[3]

7

In [38]:
sr[[0,4,2]]

0    10
4     6
2     8
dtype: int64

In [40]:
sr = pd.Series([10,9,8,7,6], index = ['a','b','c','d','e'])
sr

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [41]:
sr['c']

8

In [43]:
sr[['c','d','e']]

c    8
d    7
e    6
dtype: int64

In [45]:
sr['b':'e']

b    9
c    8
d    7
e    6
dtype: int64

In [49]:
dict_data = {'CO':100, 'MX':200, 'AR':300}
dict_data

{'AR': 300, 'CO': 100, 'MX': 200}

In [54]:
dict_data.keys()

dict_keys(['CO', 'MX', 'AR'])

In [55]:
dict_data['MX']

200

In [51]:
dict_data.values()

dict_values([100, 200, 300])

In [52]:
dict_data.items()

dict_items([('CO', 100), ('MX', 200), ('AR', 300)])

In [57]:
pd.Series(dict_data) #crear numpy Series a partir de un diccionario

CO    100
MX    200
AR    300
dtype: int64

In [61]:
sr = pd.Series(dict_data, index=['CO','MX','PE'])
sr

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [62]:
sr.isnull()

CO    False
MX    False
PE     True
dtype: bool

In [63]:
sr.notnull()

CO     True
MX     True
PE    False
dtype: bool