In [11]:
import pandas as pd
import numpy as np
pd.__version__

'1.4.1'

In [13]:
pd.options.display.float_format= '{}'.format #set float format

In [14]:
np.set_printoptions(precision=2) #set float format in pandas

In [15]:
x1 = np.random.rand(2,5) * 10 #numeros random positivos
x1

array([[1.79, 4.67, 0.91, 4.63, 1.64],
       [5.02, 0.16, 5.74, 2.96, 8.01]])

In [16]:
x2 = np.random.rand(2,5) * -1 #los pasamos a negativos.
x2

array([[-0.61, -0.12, -0.98, -0.21, -0.05],
       [-0.13, -0.34, -0.88, -0.99, -0.35]])

In [17]:
np.concatenate([x1,x2]) #concatenar en numpy a lo largo de las filas, por defecto es filas.

array([[ 1.79,  4.67,  0.91,  4.63,  1.64],
       [ 5.02,  0.16,  5.74,  2.96,  8.01],
       [-0.61, -0.12, -0.98, -0.21, -0.05],
       [-0.13, -0.34, -0.88, -0.99, -0.35]])

In [18]:
np.concatenate([x1,x2]).shape

(4, 5)

In [19]:
np.concatenate([x1,x2], axis =1) #concatenar en numpy a lo largo de columnas.

array([[ 1.79,  4.67,  0.91,  4.63,  1.64, -0.61, -0.12, -0.98, -0.21,
        -0.05],
       [ 5.02,  0.16,  5.74,  2.96,  8.01, -0.13, -0.34, -0.88, -0.99,
        -0.35]])

In [23]:
np.concatenate([x1,x2], axis =1).shape

(2, 10)

In [21]:
s1 = pd.Series(x1[0], index=['a','b', 'c', 'd','e'])
s1

a   1.7947618975986612
b   4.6707458693825785
c   0.9144038396122045
d    4.629516326587099
e   1.6388302784305198
dtype: float64

In [11]:
s2 = pd.Series(x2[0], index= ['c','d', 'e', 'f','g'])
s2

c    -0.1760471404258629
d    -0.9332165122376255
e   -0.22650834332776582
f    -0.3006136528984804
g   -0.26514938872117055
dtype: float64

In [12]:
pd.concat([s1,s2]) #concatenar en pd a lo largo de las filas, las filas estan por defecto.

a       6.96066604944027
b   0.013548372367007122
c      6.238815819928412
d      3.919051994884141
e     2.7958799734259476
c    -0.1760471404258629
d    -0.9332165122376255
e   -0.22650834332776582
f    -0.3006136528984804
g   -0.26514938872117055
dtype: float64

In [13]:
pd.concat([s1,s2], axis=1) #concatenar en pd a lo largo de las columnas.

0                    1
a     6.96066604944027                  NaN
b 0.013548372367007122                  NaN
c    6.238815819928412  -0.1760471404258629
d    3.919051994884141  -0.9332165122376255
e   2.7958799734259476 -0.22650834332776582
f                  NaN  -0.3006136528984804
g                  NaN -0.26514938872117055

In [14]:
s1.reset_index() #resetear el indice sin borrarlo.

index                    0
0     a     6.96066604944027
1     b 0.013548372367007122
2     c    6.238815819928412
3     d    3.919051994884141
4     e   2.7958799734259476

In [15]:
s1.reset_index(drop=True) #resetear el indice borrandolo.

0       6.96066604944027
1   0.013548372367007122
2      6.238815819928412
3      3.919051994884141
4     2.7958799734259476
dtype: float64

In [16]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)],axis=1) # Concatenar series

0                    1
0     6.96066604944027  -0.1760471404258629
1 0.013548372367007122  -0.9332165122376255
2    6.238815819928412 -0.22650834332776582
3    3.919051994884141  -0.3006136528984804
4   2.7958799734259476 -0.26514938872117055

In [17]:
df1 = pd.DataFrame(np.random.rand(3,2) * 10, columns=['a', 'b'])
df1

a                  b
0 4.032838581746107  3.072781776383311
1 2.670001002633444  7.883946074329203
2 6.693695105118534 3.8770759581465084

In [18]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1, columns= ['a', 'b'], index= [2,3,4])
df2

a                   b
2 -0.06448901522372485 -0.8312900579436413
3  -0.9526362475818629 -0.4150194650500646
4  -0.9360595911900632 -0.2627046239963112

In [19]:
pd.concat([df1, df2]) #concatenar dataframes por indices por defecto.

a                   b
0    4.032838581746107   3.072781776383311
1    2.670001002633444   7.883946074329203
2    6.693695105118534  3.8770759581465084
2 -0.06448901522372485 -0.8312900579436413
3  -0.9526362475818629 -0.4150194650500646
4  -0.9360595911900632 -0.2627046239963112

In [20]:
pd.concat([df1, df2], axis=1) #concatenar dataframes por columnas axis=1. # los valores nulos son valores donde no hay coincidencias en el otro dataframe

a                  b                    a  \
0 4.032838581746107  3.072781776383311                  NaN   
1 2.670001002633444  7.883946074329203                  NaN   
2 6.693695105118534 3.8770759581465084 -0.06448901522372485   
3               NaN                NaN  -0.9526362475818629   
4               NaN                NaN  -0.9360595911900632   

                    b  
0                 NaN  
1                 NaN  
2 -0.8312900579436413  
3 -0.4150194650500646  
4 -0.2627046239963112

In [21]:
pd.concat([df1,df2], axis= 1, join='inner') #inner join de 2 dataframes, solo las coincidencias de ambos dataframes.

a                  b                    a  \
2 6.693695105118534 3.8770759581465084 -0.06448901522372485   

                    b  
2 -0.8312900579436413

In [22]:
pd.concat([df1,df2], axis= 1, join='outer') #outer join de 2 dataframes, por defecto es outer, los indices que coinciden y los que no, 

a                  b                    a  \
0 4.032838581746107  3.072781776383311                  NaN   
1 2.670001002633444  7.883946074329203                  NaN   
2 6.693695105118534 3.8770759581465084 -0.06448901522372485   
3               NaN                NaN  -0.9526362475818629   
4               NaN                NaN  -0.9360595911900632   

                    b  
0                 NaN  
1                 NaN  
2 -0.8312900579436413  
3 -0.4150194650500646  
4 -0.2627046239963112

In [23]:
pd.concat(
    [
    df1.reset_index(drop=True),
    df2.reset_index(drop=True)
    ], axis= 1)

a                  b                    a  \
0 4.032838581746107  3.072781776383311 -0.06448901522372485   
1 2.670001002633444  7.883946074329203  -0.9526362475818629   
2 6.693695105118534 3.8770759581465084  -0.9360595911900632   

                    b  
0 -0.8312900579436413  
1 -0.4150194650500646  
2 -0.2627046239963112

In [24]:
df1.append(df2) #se oega la segunda matriz debajo de la primera.

C:\Users\luisp\AppData\Local\Temp/ipykernel_25396/1902554926.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2) #se oega la segunda matriz debajo de la primera.


a                   b
0    4.032838581746107   3.072781776383311
1    2.670001002633444   7.883946074329203
2    6.693695105118534  3.8770759581465084
2 -0.06448901522372485 -0.8312900579436413
3  -0.9526362475818629 -0.4150194650500646
4  -0.9360595911900632 -0.2627046239963112

In [25]:
df1.T# transponer un dataframe.

0                 1                  2
a 4.032838581746107 2.670001002633444  6.693695105118534
b 3.072781776383311 7.883946074329203 3.8770759581465084

In [26]:
df1.T.append(df2.T).T #concetenar data frames a lo largo de columnas.

C:\Users\luisp\AppData\Local\Temp/ipykernel_25396/2255709428.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.T.append(df2.T).T #concetenar data frames a lo largo de columnas.


a                  b                    a  \
0 4.032838581746107  3.072781776383311                  NaN   
1 2.670001002633444  7.883946074329203                  NaN   
2 6.693695105118534 3.8770759581465084 -0.06448901522372485   
3               NaN                NaN  -0.9526362475818629   
4               NaN                NaN  -0.9360595911900632   

                    b  
0                 NaN  
1                 NaN  
2 -0.8312900579436413  
3 -0.4150194650500646  
4 -0.2627046239963112

In [27]:
df1

a                  b
0 4.032838581746107  3.072781776383311
1 2.670001002633444  7.883946074329203
2 6.693695105118534 3.8770759581465084

In [28]:
df2

a                   b
2 -0.06448901522372485 -0.8312900579436413
3  -0.9526362475818629 -0.4150194650500646
4  -0.9360595911900632 -0.2627046239963112

In [29]:
df1.update(df2) #actualizar datos de un data frame con otro en las filas que coincidan, como un left join.
df1

a                   b
0    4.032838581746107   3.072781776383311
1    2.670001002633444   7.883946074329203
2 -0.06448901522372485 -0.8312900579436413

In [32]:
#Otra forma de hacer un append mas directo y más personalizado,
#1 la posicion (1) indica que será la segunda fila (empieza a contar desde cero) 
#2 luego sigue el nombre de la nueva columna
#3 luego los valores de la nueva columna
df2.insert(1, 'columna_nueva2', [45, 10, 67])

In [33]:
df2

a  columna_nueva2                   b
2 -0.06448901522372485              45 -0.8312900579436413
3  -0.9526362475818629              10 -0.4150194650500646
4  -0.9360595911900632              67 -0.2627046239963112